name: planta_externa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  file_picker: ^10.3.3
  archive: ^4.0.7
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  http: ^1.1.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_pdfview: ^1.3.2
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/manuals/